	soc_system u0 (
		.alt_vip_itc_0_clocked_video_vid_clk       (<connected-to-alt_vip_itc_0_clocked_video_vid_clk>),       //    alt_vip_itc_0_clocked_video.vid_clk
		.alt_vip_itc_0_clocked_video_vid_data      (<connected-to-alt_vip_itc_0_clocked_video_vid_data>),      //                               .vid_data
		.alt_vip_itc_0_clocked_video_underflow     (<connected-to-alt_vip_itc_0_clocked_video_underflow>),     //                               .underflow
		.alt_vip_itc_0_clocked_video_vid_datavalid (<connected-to-alt_vip_itc_0_clocked_video_vid_datavalid>), //                               .vid_datavalid
		.alt_vip_itc_0_clocked_video_vid_v_sync    (<connected-to-alt_vip_itc_0_clocked_video_vid_v_sync>),    //                               .vid_v_sync
		.alt_vip_itc_0_clocked_video_vid_h_sync    (<connected-to-alt_vip_itc_0_clocked_video_vid_h_sync>),    //                               .vid_h_sync
		.alt_vip_itc_0_clocked_video_vid_f         (<connected-to-alt_vip_itc_0_clocked_video_vid_f>),         //                               .vid_f
		.alt_vip_itc_0_clocked_video_vid_h         (<connected-to-alt_vip_itc_0_clocked_video_vid_h>),         //                               .vid_h
		.alt_vip_itc_0_clocked_video_vid_v         (<connected-to-alt_vip_itc_0_clocked_video_vid_v>),         //                               .vid_v
		.button_pio_external_connection_export     (<connected-to-button_pio_external_connection_export>),     // button_pio_external_connection.export
		.clk_clk                                   (<connected-to-clk_clk>),                                   //                            clk.clk
		.clk_130_clk                               (<connected-to-clk_130_clk>),                               //                        clk_130.clk
		.ctrl_acknowledge                          (<connected-to-ctrl_acknowledge>),                          //                           ctrl.acknowledge
		.ctrl_irq                                  (<connected-to-ctrl_irq>),                                  //                               .irq
		.ctrl_address                              (<connected-to-ctrl_address>),                              //                               .address
		.ctrl_bus_enable                           (<connected-to-ctrl_bus_enable>),                           //                               .bus_enable
		.ctrl_byte_enable                          (<connected-to-ctrl_byte_enable>),                          //                               .byte_enable
		.ctrl_rw                                   (<connected-to-ctrl_rw>),                                   //                               .rw
		.ctrl_write_data                           (<connected-to-ctrl_write_data>),                           //                               .write_data
		.ctrl_read_data                            (<connected-to-ctrl_read_data>),                            //                               .read_data
		.dipsw_pio_external_connection_export      (<connected-to-dipsw_pio_external_connection_export>),      //  dipsw_pio_external_connection.export
		.hps_0_f2h_cold_reset_req_reset_n          (<connected-to-hps_0_f2h_cold_reset_req_reset_n>),          //       hps_0_f2h_cold_reset_req.reset_n
		.hps_0_f2h_debug_reset_req_reset_n         (<connected-to-hps_0_f2h_debug_reset_req_reset_n>),         //      hps_0_f2h_debug_reset_req.reset_n
		.hps_0_f2h_stm_hw_events_stm_hwevents      (<connected-to-hps_0_f2h_stm_hw_events_stm_hwevents>),      //        hps_0_f2h_stm_hw_events.stm_hwevents
		.hps_0_f2h_warm_reset_req_reset_n          (<connected-to-hps_0_f2h_warm_reset_req_reset_n>),          //       hps_0_f2h_warm_reset_req.reset_n
		.hps_0_h2f_reset_reset_n                   (<connected-to-hps_0_h2f_reset_reset_n>),                   //                hps_0_h2f_reset.reset_n
		.hps_0_hps_io_hps_io_emac1_inst_TX_CLK     (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CLK>),     //                   hps_0_hps_io.hps_io_emac1_inst_TX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_TXD0       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD0>),       //                               .hps_io_emac1_inst_TXD0
		.hps_0_hps_io_hps_io_emac1_inst_TXD1       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD1>),       //                               .hps_io_emac1_inst_TXD1
		.hps_0_hps_io_hps_io_emac1_inst_TXD2       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD2>),       //                               .hps_io_emac1_inst_TXD2
		.hps_0_hps_io_hps_io_emac1_inst_TXD3       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TXD3>),       //                               .hps_io_emac1_inst_TXD3
		.hps_0_hps_io_hps_io_emac1_inst_RXD0       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD0>),       //                               .hps_io_emac1_inst_RXD0
		.hps_0_hps_io_hps_io_emac1_inst_MDIO       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDIO>),       //                               .hps_io_emac1_inst_MDIO
		.hps_0_hps_io_hps_io_emac1_inst_MDC        (<connected-to-hps_0_hps_io_hps_io_emac1_inst_MDC>),        //                               .hps_io_emac1_inst_MDC
		.hps_0_hps_io_hps_io_emac1_inst_RX_CTL     (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CTL>),     //                               .hps_io_emac1_inst_RX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_TX_CTL     (<connected-to-hps_0_hps_io_hps_io_emac1_inst_TX_CTL>),     //                               .hps_io_emac1_inst_TX_CTL
		.hps_0_hps_io_hps_io_emac1_inst_RX_CLK     (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RX_CLK>),     //                               .hps_io_emac1_inst_RX_CLK
		.hps_0_hps_io_hps_io_emac1_inst_RXD1       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD1>),       //                               .hps_io_emac1_inst_RXD1
		.hps_0_hps_io_hps_io_emac1_inst_RXD2       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD2>),       //                               .hps_io_emac1_inst_RXD2
		.hps_0_hps_io_hps_io_emac1_inst_RXD3       (<connected-to-hps_0_hps_io_hps_io_emac1_inst_RXD3>),       //                               .hps_io_emac1_inst_RXD3
		.hps_0_hps_io_hps_io_sdio_inst_CMD         (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CMD>),         //                               .hps_io_sdio_inst_CMD
		.hps_0_hps_io_hps_io_sdio_inst_D0          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D0>),          //                               .hps_io_sdio_inst_D0
		.hps_0_hps_io_hps_io_sdio_inst_D1          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D1>),          //                               .hps_io_sdio_inst_D1
		.hps_0_hps_io_hps_io_sdio_inst_CLK         (<connected-to-hps_0_hps_io_hps_io_sdio_inst_CLK>),         //                               .hps_io_sdio_inst_CLK
		.hps_0_hps_io_hps_io_sdio_inst_D2          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D2>),          //                               .hps_io_sdio_inst_D2
		.hps_0_hps_io_hps_io_sdio_inst_D3          (<connected-to-hps_0_hps_io_hps_io_sdio_inst_D3>),          //                               .hps_io_sdio_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D0          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D0>),          //                               .hps_io_usb1_inst_D0
		.hps_0_hps_io_hps_io_usb1_inst_D1          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D1>),          //                               .hps_io_usb1_inst_D1
		.hps_0_hps_io_hps_io_usb1_inst_D2          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D2>),          //                               .hps_io_usb1_inst_D2
		.hps_0_hps_io_hps_io_usb1_inst_D3          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D3>),          //                               .hps_io_usb1_inst_D3
		.hps_0_hps_io_hps_io_usb1_inst_D4          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D4>),          //                               .hps_io_usb1_inst_D4
		.hps_0_hps_io_hps_io_usb1_inst_D5          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D5>),          //                               .hps_io_usb1_inst_D5
		.hps_0_hps_io_hps_io_usb1_inst_D6          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D6>),          //                               .hps_io_usb1_inst_D6
		.hps_0_hps_io_hps_io_usb1_inst_D7          (<connected-to-hps_0_hps_io_hps_io_usb1_inst_D7>),          //                               .hps_io_usb1_inst_D7
		.hps_0_hps_io_hps_io_usb1_inst_CLK         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_CLK>),         //                               .hps_io_usb1_inst_CLK
		.hps_0_hps_io_hps_io_usb1_inst_STP         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_STP>),         //                               .hps_io_usb1_inst_STP
		.hps_0_hps_io_hps_io_usb1_inst_DIR         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_DIR>),         //                               .hps_io_usb1_inst_DIR
		.hps_0_hps_io_hps_io_usb1_inst_NXT         (<connected-to-hps_0_hps_io_hps_io_usb1_inst_NXT>),         //                               .hps_io_usb1_inst_NXT
		.hps_0_hps_io_hps_io_spim1_inst_CLK        (<connected-to-hps_0_hps_io_hps_io_spim1_inst_CLK>),        //                               .hps_io_spim1_inst_CLK
		.hps_0_hps_io_hps_io_spim1_inst_MOSI       (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MOSI>),       //                               .hps_io_spim1_inst_MOSI
		.hps_0_hps_io_hps_io_spim1_inst_MISO       (<connected-to-hps_0_hps_io_hps_io_spim1_inst_MISO>),       //                               .hps_io_spim1_inst_MISO
		.hps_0_hps_io_hps_io_spim1_inst_SS0        (<connected-to-hps_0_hps_io_hps_io_spim1_inst_SS0>),        //                               .hps_io_spim1_inst_SS0
		.hps_0_hps_io_hps_io_uart0_inst_RX         (<connected-to-hps_0_hps_io_hps_io_uart0_inst_RX>),         //                               .hps_io_uart0_inst_RX
		.hps_0_hps_io_hps_io_uart0_inst_TX         (<connected-to-hps_0_hps_io_hps_io_uart0_inst_TX>),         //                               .hps_io_uart0_inst_TX
		.hps_0_hps_io_hps_io_i2c0_inst_SDA         (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SDA>),         //                               .hps_io_i2c0_inst_SDA
		.hps_0_hps_io_hps_io_i2c0_inst_SCL         (<connected-to-hps_0_hps_io_hps_io_i2c0_inst_SCL>),         //                               .hps_io_i2c0_inst_SCL
		.hps_0_hps_io_hps_io_i2c1_inst_SDA         (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SDA>),         //                               .hps_io_i2c1_inst_SDA
		.hps_0_hps_io_hps_io_i2c1_inst_SCL         (<connected-to-hps_0_hps_io_hps_io_i2c1_inst_SCL>),         //                               .hps_io_i2c1_inst_SCL
		.hps_0_hps_io_hps_io_gpio_inst_GPIO09      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO09>),      //                               .hps_io_gpio_inst_GPIO09
		.hps_0_hps_io_hps_io_gpio_inst_GPIO35      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO35>),      //                               .hps_io_gpio_inst_GPIO35
		.hps_0_hps_io_hps_io_gpio_inst_GPIO40      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO40>),      //                               .hps_io_gpio_inst_GPIO40
		.hps_0_hps_io_hps_io_gpio_inst_GPIO53      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO53>),      //                               .hps_io_gpio_inst_GPIO53
		.hps_0_hps_io_hps_io_gpio_inst_GPIO54      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO54>),      //                               .hps_io_gpio_inst_GPIO54
		.hps_0_hps_io_hps_io_gpio_inst_GPIO61      (<connected-to-hps_0_hps_io_hps_io_gpio_inst_GPIO61>),      //                               .hps_io_gpio_inst_GPIO61
		.led_pio_external_connection_export        (<connected-to-led_pio_external_connection_export>),        //    led_pio_external_connection.export
		.memory_mem_a                              (<connected-to-memory_mem_a>),                              //                         memory.mem_a
		.memory_mem_ba                             (<connected-to-memory_mem_ba>),                             //                               .mem_ba
		.memory_mem_ck                             (<connected-to-memory_mem_ck>),                             //                               .mem_ck
		.memory_mem_ck_n                           (<connected-to-memory_mem_ck_n>),                           //                               .mem_ck_n
		.memory_mem_cke                            (<connected-to-memory_mem_cke>),                            //                               .mem_cke
		.memory_mem_cs_n                           (<connected-to-memory_mem_cs_n>),                           //                               .mem_cs_n
		.memory_mem_ras_n                          (<connected-to-memory_mem_ras_n>),                          //                               .mem_ras_n
		.memory_mem_cas_n                          (<connected-to-memory_mem_cas_n>),                          //                               .mem_cas_n
		.memory_mem_we_n                           (<connected-to-memory_mem_we_n>),                           //                               .mem_we_n
		.memory_mem_reset_n                        (<connected-to-memory_mem_reset_n>),                        //                               .mem_reset_n
		.memory_mem_dq                             (<connected-to-memory_mem_dq>),                             //                               .mem_dq
		.memory_mem_dqs                            (<connected-to-memory_mem_dqs>),                            //                               .mem_dqs
		.memory_mem_dqs_n                          (<connected-to-memory_mem_dqs_n>),                          //                               .mem_dqs_n
		.memory_mem_odt                            (<connected-to-memory_mem_odt>),                            //                               .mem_odt
		.memory_mem_dm                             (<connected-to-memory_mem_dm>),                             //                               .mem_dm
		.memory_oct_rzqin                          (<connected-to-memory_oct_rzqin>),                          //                               .oct_rzqin
		.reset_reset_n                             (<connected-to-reset_reset_n>),                             //                          reset.reset_n
		.sts_acknowledge                           (<connected-to-sts_acknowledge>),                           //                            sts.acknowledge
		.sts_irq                                   (<connected-to-sts_irq>),                                   //                               .irq
		.sts_address                               (<connected-to-sts_address>),                               //                               .address
		.sts_bus_enable                            (<connected-to-sts_bus_enable>),                            //                               .bus_enable
		.sts_byte_enable                           (<connected-to-sts_byte_enable>),                           //                               .byte_enable
		.sts_rw                                    (<connected-to-sts_rw>),                                    //                               .rw
		.sts_write_data                            (<connected-to-sts_write_data>),                            //                               .write_data
		.sts_read_data                             (<connected-to-sts_read_data>),                             //                               .read_data
		.buf0_1_export                             (<connected-to-buf0_1_export>),                             //                         buf0_1.export
		.buf1_export                               (<connected-to-buf1_export>),                               //                           buf1.export
		.buf0_export                               (<connected-to-buf0_export>),                               //                           buf0.export
		.ra_status_export                          (<connected-to-ra_status_export>),                          //                      ra_status.export
		.de_status_export                          (<connected-to-de_status_export>),                          //                      de_status.export
		.ra_count_export                           (<connected-to-ra_count_export>),                           //                       ra_count.export
		.de_count_export                           (<connected-to-de_count_export>),                           //                       de_count.export
		.de_counter_load_export                    (<connected-to-de_counter_load_export>),                    //                de_counter_load.export
		.de_counter_load_1_export                  (<connected-to-de_counter_load_1_export>),                  //              de_counter_load_1.export
		.de_counter_max_export                     (<connected-to-de_counter_max_export>),                     //                 de_counter_max.export
		.ra_counter_max_export                     (<connected-to-ra_counter_max_export>),                     //                 ra_counter_max.export
		.de_cmdcontrol_export                      (<connected-to-de_cmdcontrol_export>),                      //                  de_cmdcontrol.export
		.ra_cmdcontrol_export                      (<connected-to-ra_cmdcontrol_export>),                      //                  ra_cmdcontrol.export
		.de_cmdduration_export                     (<connected-to-de_cmdduration_export>),                     //                 de_cmdduration.export
		.ra_cmdduration_export                     (<connected-to-ra_cmdduration_export>),                     //                 ra_cmdduration.export
		.de_trackctrl_export                       (<connected-to-de_trackctrl_export>),                       //                   de_trackctrl.export
		.ra_trackctrl_export                       (<connected-to-ra_trackctrl_export>),                       //                   ra_trackctrl.export
		.de_cmdtick_export                         (<connected-to-de_cmdtick_export>),                         //                     de_cmdtick.export
		.ra_cmdtick_export                         (<connected-to-ra_cmdtick_export>),                         //                     ra_cmdtick.export
		.de_backlash_tick_export                   (<connected-to-de_backlash_tick_export>),                   //               de_backlash_tick.export
		.ra_backlash_tick_export                   (<connected-to-ra_backlash_tick_export>),                   //               ra_backlash_tick.export
		.de_backlash_duration_export               (<connected-to-de_backlash_duration_export>),               //           de_backlash_duration.export
		.ra_backlash_duration_export               (<connected-to-ra_backlash_duration_export>)                //           ra_backlash_duration.export
	);

